-- 刪除舊表（避免重複建立錯誤）
IF OBJECT_ID('Replies') IS NOT NULL DROP TABLE Replies;
IF OBJECT_ID('Topics')  IS NOT NULL DROP TABLE Topics;
IF OBJECT_ID('Users')   IS NOT NULL DROP TABLE Users;
GO

-- 使用者
CREATE TABLE Users (
    UserID INT IDENTITY PRIMARY KEY,
    UserName NVARCHAR(50) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(64) NOT NULL
);

-- 主題
CREATE TABLE Topics (
    TopicID INT IDENTITY PRIMARY KEY,
    UserID INT NOT NULL,
    Title NVARCHAR(200) NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

-- 回覆
CREATE TABLE Replies (
    ReplyID INT IDENTITY PRIMARY KEY,
    TopicID INT NOT NULL,
    UserID INT NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (TopicID) REFERENCES Topics(TopicID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);